version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 7b24afc8bc80e548d66c4e7ff72171c5
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: ba9dafc215bc83c90d6cd8ac4dd86d02
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
  php:
    image: php:apache
    container_name: my_php
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: example